amr:
  
 joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

 left_wheel_vel_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

 right_wheel_vel_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

 mobile_base_controller:
    type        : diff_drive_controller/DiffDriveController
    left_wheel  : 'left_wheel_joint'
    right_wheel : 'right_wheel_joint'
    publish_rate: 50               # default: 50
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    #pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    #twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    
    allow_multiple_cmd_vel_publishers: true
    odom_frame_id: odom
    base_frame_id: base_link
    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.45
    wheel_radius : 0.051
    publish_cmd : true

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0
 
    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 0.5
 
    # Base frame_id #default: base_link

    open_loop: false
    enable_odom_tf: false
 
    # Velocity and acceleration limitss
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.45  # m/s
        min_velocity           : -0.45 # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.225 # m/s^2
        min_acceleration       : -0.225 # m/s^2
        has_jerk_limits        : false
        max_jerk               : 1.0  # m/s^3
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.96 # rad/s
        has_acceleration_limits: true
        max_acceleration       : 0.98  # rad/s^2
        has_jerk_limits        : false
        max_jerk               : 3.92 # rad/s^3